config/routes.rb
require 'sidekiq/web'
require 'sidekiq-scheduler/web'

Rails.application.routes.draw do
  root "tweets#index"

  resources :users
  resources :tweets

  get '/welcome', to: 'welcome#index'
  get '/auth/:provider/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  mount Sidekiq::Web => '/sidekiq', constraints: lambda { |req|
    # FIXME: user.admin? で管理者かどうかを判断できるようにする
    req.session['user_id'].present? and req.session['user_id'] == 3
  }

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/tweet.rb
require 'open-uri'

# == Schema Information
#
# Table name: tweets
#
#  id                  :bigint           not null, primary key
#  t_id                :string
#  body                :text
#  url                 :string
#  raw_json            :text
#  media_type          :string
#  classification      :string
#  classified          :boolean
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  first_media_url     :string
#  user_id             :bigint
#  original_created_at :datetime
#
class Tweet < ApplicationRecord
  # こんなかんじで定数の一覧がとれる
  #
  # Tweet::Classification.constants.each do |k|
  #   p Tweet::Classification.const_get(k)
  # end
  #
  # スレミオ分類
  # FIXME: Concernにくくりだすのがいいかも？
  # FIXME: Solargraphが定数を拾ってこれないのでうまみがない. ベタ書きしたほうがいいかも
  module Classification
    [
      :SULETTA,  # スレッタ単体
      :MIORINE,  # ミオリネ単体
      :SULEMIO,  # スレミオ
      :OTHER,     # それ以外
      :NOTSULEMIO # スレミオではない
      #:WITHHOLD, # 判断を保留する（心がふたつあるんじゃ）
    ].each do |k|
      const_set(k, k.to_s.downcase.freeze)
    end

    def self.constants_hash
      constants.map do |k|
        [k, const_get(k)]
      end.to_h
    end
  end

  # 表現されているものの種類
  module ContentType
    module Photo
      [
        :ILLUSTRATION, # イラスト（マンガではない絵）
        :MANGA,        # マンガ
        :NOVEL,        # 画像化された小説
        :OTHER         # 本編キャプチャによる萌え語り, フィギュアやプラモの撮影など？
      ].each do |k|
        const_set(k, k.to_s.downcase.freeze)
      end
    end

    def self.constants_hash
      constants.map do |k|
        [k, const_get(k)]
      end.to_h
    end
  end

  # メディアタイプ（画像つきのツィートかどうか）
  module MediaType
    [
      :PHOTO,   # 画像つきツィート
      :NONE,    # メディアの無いツィート
      :OTHER    # その他のツィート
    ].each do |k|
      const_set(k, k.to_s.downcase.freeze)
    end

    def self.constants_hash
      constants.map do |k|
        [k, const_get(k)]
      end.to_h
    end
  end

  belongs_to :user, optional: true
  has_many :classify_results, dependent: :destroy
  has_many :sulemio_by_ml_classify_results,
           -> { where(by_ml: true, classification: Classification::SULEMIO, result: true) },
           class_name: 'ClassifyResult'
  has_many :by_user_classify_results,
           -> { where(by_ml: false) },
           class_name: 'ClassifyResult'

  validates :t_id, uniqueness: true, presence: true

  attribute :a_classification, :string # 元々あったclassificationのかわりに使う
  attribute :classified, default: false

  scope :unprotected, -> { preload(:user).preload(:classify_results).joins(:user).where(users: { protected: false }) }
  scope :with_photo, lambda {
    unprotected.where(media_type: Tweet::MediaType::PHOTO)
  }
  scope :classified_with_photo, lambda { |classification, result|
    with_photo
      .joins(:classify_results)
      .where(classify_results: { classification: classification, result: result, by_ml: false })
  }
  scope :pre_classified_with_photo, lambda { |classification, result|
    subquery = with_photo
               .joins(:classify_results).where(classify_results: { classification: classification, by_ml: false })
    with_photo
      .joins(:classify_results)
      .where(classify_results: { classification: classification, result: result, by_ml: true })
      .where.not(id: subquery)
  }
  scope :unclassified_with_photo, lambda {
    with_photo
      .left_outer_joins(:classify_results)
      .where(classify_results: { id: nil })
  }
  scope :pre_classified_with_sulemio_photo, lambda {
    # FIXME: pre_classified_with_photo を使うようになおしたい
    #pre_classified_with_photo(ClassifyResult::Classification::SULEMIO, true)
    preload(:classify_results)
      .joins(:user)
      .where(users: { protected: false })
      .where(media_type: Tweet::MediaType::PHOTO)
      .joins(:sulemio_by_ml_classify_results)
      .left_outer_joins(:by_user_classify_results)
      .where(by_user_classify_results: { tweet_id: nil })
  }
  scope :pre_classified_with_notsulemio_photo, lambda {
    pre_classified_with_photo(ClassifyResult::Classification::SULEMIO, false)
  }
  scope :classified_with_sulemio_photo, lambda {
    classified_with_photo(ClassifyResult::Classification::SULEMIO, true)
  }
  scope :classified_with_notsulemio_photo, lambda {
    classified_with_photo(ClassifyResult::Classification::SULEMIO, false)
  }
  scope :with_photo_without_user, lambda {
    where(media_type: Tweet::MediaType::PHOTO)
      .left_outer_joins(:user)
      .where(users: { id: nil })
  }
  # FIXME: start_date, end_date をStringで受け取るべきなのか再検討する
  # FIXME: テストを書く
  scope :by_date, lambda { |start_date, end_date|
    tweets = where.not(original_created_at: nil)
    if start_date.present? && end_date.present?
      tweets.where(original_created_at: DateTime.parse(start_date)..DateTime.parse(end_date))
    elsif start_date.present?
      tweets.where('original_created_at >= ?', DateTime.parse(start_date))
    elsif end_date.present?
      tweets.where('original_created_at <= ?', DateTime.parse(end_date))
    else
      tweets
    end
  }

  before_save do
    if classification
      self.classified = true
    end

    self.url ||= "https://twitter.com/_/status/#{t_id}"
  end

  # ユーザによる判断が存在する場合にtrueを返す
  # includes(:classify_results) しておく必要がある
  def classified?
    classify_results.map(&:by_ml).include?(false)
  end

  # ユーザによってスレミオだと判断されている場合にtrueを返す
  def sulemio?
    classified_for?(Classification::SULEMIO)
  end

  # ユーザによってミオリネだと判断されている場合にtrueを返す
  def miorine?
    classified_for?(Classification::MIORINE)
  end

  # ユーザによってスレッタだと判断されている場合にtrueを返す
  def suletta?
    classified_for?(Classification::SULETTA)
  end

  # ユーザによってclassificationだと判断されている場合にtrueを返す
  # includes(:classify_results) しておく必要がある
  # FIXME: classify_resultsの数が増えるとまずいかも？
  def classified_for?(classification)
    user_crs = classify_results.reject{ |cr| cr.by_ml }.select { |cr| cr.classification == classification }
    true_count = user_crs.count { |cr| cr.result }
    false_count = user_crs.count { |cr| !cr.result }
    ratio = true_count.to_f / (true_count + false_count)
    return ratio >= 0.5
  end

  def media_keys
    if raw_json
      h = JSON.parse(raw_json).deep_symbolize_keys
      if h.key?(:attachments)
        attachments = h[:attachments]
        if attachments.key?(:media_keys)
          return attachments[:media_keys]
        end
      end
    end
    return nil
  end

  def media_count
    keys = media_keys
    if keys
      return keys.count
    else
      return 0
    end
  end

  # api_response is a hash
  def self.create_many_from_api_response(tweets_response)
    tweets = tweets_response.bare_tweets
    tweets = tweets.map do |t|
      media_type = tweets_response.media_type_for_tweet(t)
      case media_type
      in Tweet::MediaType::PHOTO
        first_media_url = tweets_response.first_media_url_for_tweet(t)
      else
        first_media_url = nil
      end

      Tweet.find_or_create_with(
        tweet_hash: t,
        media_type: media_type,
        first_media_url: first_media_url
      )
    end
    Rails.logger.info "#{tweets.count} tweets inserted"
    return tweets
  end

  # 1ツィートを表すHashからレコードを検索する
  # レコードが存在しなければ, 1ツィートを表すHashとメディアタイプから新規レコードを追加する
  def self.find_or_create_with(tweet_hash:, media_type:, first_media_url: nil)
    tweet_hash = tweet_hash.with_indifferent_access
    case [tweet_hash, media_type]
    in [{ id: String => t_id, text: String => text }, MediaType::PHOTO | MediaType::NONE | MediaType::OTHER]
      user = User.find_or_create_by_uid(tweet_hash[:author_id]) if tweet_hash[:author_id]
      tweet = Tweet.find_or_initialize_by(t_id: t_id)
      tweet.body = text
      tweet.raw_json = tweet_hash.to_json
      tweet.media_type = media_type
      tweet.first_media_url = first_media_url
      tweet.original_created_at = tweet_hash[:created_at]
      tweet.user = user
      tweet.save! # 保存に失敗したら例外を投げる
      tweet
    end
  end

  # 検索で見つかったツィートを保存する
  # @param [User] access_user Twitter APIにアクセスするのに使用するユーザー
  # @param [String] query ツィート検索クエリ
  # @param [Integer] count 遡るページ数
  def self.save_searched_tweets(access_user:, query:, count: 1, pagination_token: nil)
    next_token = pagination_token
    count.times do
      _, next_token = save_searched_tweets_page(
        access_user: access_user,
        query: query,
        pagination_token: next_token
      )
      break if next_token.nil?
    end

    return next_token
  end

  # 検索で見つかったツィートを保存する（1ページ分）
  # @param [User] access_user Twitter APIにアクセスするのに使用するユーザー
  # @param [String] query ツィート検索クエリ
  # @param [String] pagination_token 次のページを取得するためのトークン
  def self.save_searched_tweets_page(access_user:, query:, pagination_token:)
    token = access_user.credential.token
    res = TwitterAPI::Client.tweets_search_recent(token, query, pagination_token)
    tweets_response = TwitterAPI::TweetsResponse.new(res)
    tweets = Tweet.create_many_from_api_response(tweets_response)
    return tweets, tweets_response.next_token
  end

  # ユーザーがnilのツィートを一括で更新する
  #
  # @param [User] access_user Twitter APIにアクセスするのに使用するユーザー
  # @return [Array<Tweet>] 更新したツィートの配列
  def self.bulk_update_has_no_user(access_user:, offset: 0, limit: 1000)
    tweet_has_no_user = where(media_type: Tweet::MediaType::PHOTO)
                        .order(created_at: :desc)
                        .left_outer_joins(:user)
                        .where(users: { id: nil })
                        .offset(offset)
                        .limit(limit)
    ret = []
    tweet_has_no_user.each_slice(100) do |tweets|
      response_hash = TwitterAPI::Client.tweets(access_user.credential.token, tweets.map(&:t_id))
      tweets_response = TwitterAPI::TweetsResponse.new(response_hash)
      ret += Tweet.create_many_from_api_response(tweets_response)
    end
    return ret
  end

  # t_id が重複しているツィートをcreated_atが最新のひとつを残して削除する
  def self.delete_duplicate_tweets(count: 1000)
    Tweet.group(:t_id).having('count(*) > 1').count.take(count).map do |t_id, _|

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  include Pundit::Authorization

  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    redirect_to welcome_url unless current_user

    # スコープ(デフォルトはAI仮判断済みのスレミオ画像)
    @scope = params[:scope] || "pre_classified_with_sulemio_photo"
    # 判断モード(デフォルトはスレミオ)
    @dmode = params[:dmode] || "sulemio"
    @start_time = params[:start_time]
    @end_time = params[:end_time]
    @tweets = case @scope
              when "with_photo"
                # 画像つきの全てのツィートを表示する
                Tweet.with_photo
                     .by_date(@start_time, @end_time)
                     .order(original_created_at: :desc).page(params[:page])
              when "classified_with_sulemio_photo"
                # ユーザによるスレミオ判定済みの画像を表示する
                Tweet.classified_with_sulemio_photo
                     .by_date(@start_time, @end_time)
                     .order(original_created_at: :desc).page(params[:page])
              when "pre_classified_with_sulemio_photo"
                # AI仮判断済みのスレミオ画像を表示する
                Tweet.pre_classified_with_sulemio_photo
                     .by_date(@start_time, @end_time)
                     .order(original_created_at: :desc).page(params[:page])
              when "pre_classified_with_notsulemio_photo"
                # AI仮判断済みのスレミオ以外の画像を表示する
                Tweet.pre_classified_with_notsulemio_photo
                     .by_date(@start_time, @end_time)
                     .order(original_created_at: :desc).page(params[:page])
              else
                # リクエストエラー
                raise ActionController::BadRequest
              end
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    authorize @tweet
  end

  # GET /tweets/new
  def new
    # FIXME: ツィートの手動追加は後ほど実装する
    @tweet = Tweet.new
    authorize @tweet
  end

  # GET /tweets/1/edit
  def edit
    authorize @tweet
  end

  # FIXME: ツィートの手動追加は後ほど実装する
  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    authorize @tweet

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    authorize @tweet

    # FIXME: SULEMIO以外の判断もやろうとするとこれだとまずい
    classify_result = @tweet.classify_results.find_or_initialize_by(
      user: current_user,
      classification: ClassifyResult::Classification::SULEMIO
    )
    classify_result.result = tweet_params[:a_classification] == ClassifyResult::Classification::SULEMIO
    # FIXME: ここでsave!してるのは怪しすぎる
    classify_result.save!

    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    # FIXME: 認可は必ず失敗するようになっている. 後ほど管理権限のあるユーザーのみ削除できるようにする
    authorize @tweet

    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  # before_actionで呼び出される
  def set_tweet
    @tweet = Tweet.find(params[:id])
    @tweet.a_classification = @tweet.classify_results.find_by(user: current_user, result: true)&.classification
  end

  # 許可するパラメーターのリスト
  def tweet_params
    params.require(:tweet).permit(:a_classification)
  end
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mt-3">
    <%= form.label :a_classification, class: "form-label" %>
    <%= form.select :a_classification, options_for_select([["スレミオ", "sulemio"], ["not ｽﾚﾐｵ", "notsulemio"]]), {}, { class: "form-select" } %>
  </div>

  <div class="mt-4">
    <%= link_to "キャンセル", @tweet, class: "btn btn-secondary" %>
    <%= form.submit "保存", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<%= turbo_frame_tag(tweet) do %>
  <div class="col h-100">
    <%= render( TweetComponent.new(tweet) ) %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1 class="mt-3 mb-3">ツィートの情報を編集</h1>

<%= image_tag @tweet.first_media_url || "", class: "w-100 border" %>
<p class="mt-3 mb-3"><%= @tweet.body %></p>

<%= render "form", tweet: @tweet %>

app/views/tweets/index.html.erb
<% if @scope == "classified_with_sulemio_photo" %>
  <h1 class="mt-4 mb-3">スレミオ&#x1f99d;&#x1f345;の画像投稿</h1>
  <p>みんなでスレミオだと判断した画像ツィートです</p>
<% elsif @scope == "pre_classified_with_sulemio_photo" %>
  <h1 class="mt-4 mb-3">スレミオ&#x1f99d;&#x1f345;の画像投稿（AIによる仮判断）</h1>
  <p>意思拡張AIが<b>スレミオだ</b>と判断した画像ツィートです。<br>
  判断結果があっていたら「スレミオ」を、間違っていたら「Not ｽﾚﾐｵ」を押して正解を教えてあげてください。</p>
<% elsif @scope == "pre_classified_with_notsulemio_photo" %>
  <h1 class="mt-4 mb-3">&#x1f99d;スレミオではない&#x1f345;画像投稿（AIによる仮判断）</h1>
  <p>意思拡張AIが<b>スレミオではない</b>と判断した画像ツィートです。<br>
  判断結果があっていたら「スレミオ」を、間違っていたら「Not ｽﾚﾐｵ」を押して正解を教えてあげてください。</p>
<% elsif @scope == "suletta" %>
  <h1 class="mt-4 mb-3">スレッタ&#x1f99d;の画像投稿</h1>
  <p>みんなでスレッタだと判断した画像ツィートです</p>
<% elsif @scope == "miorine" %>
  <h1 class="mt-4 mb-3">ミオリネ&#x1f345;の画像投稿</h1>
  <p>みんなでミオリネだと判断した画像ツィートです</p>
<% elsif @scope == "with_photo" %>
  <h1 class="mt-4 mb-3">全ての画像</h1>
  <p>収集済みの全ての画像ツィートです</p>
<% end %>

<!-- FIXME: SQLチューニングして速くするの簡単じゃないかも？キャッシュかLazy Loadingを検討する -->
<!-- FIXME: countがスロークエリなのを簡単に解決できそうにないので, いちばん遅いうえにあまり意味のないscopeでcountしないようにしてる -->
<% unless @scope == "pre_classified_with_sulemio_photo" %>
  <p><%= @tweets.total_count %> ツィート</p>
<% end %>

<%= turbo_frame_tag "page_handler" %>
<div id="tweets"
     class="row row-cols-1 row-cols-md-2 row-cols-xl-3 g-3 mb-5"
     data-controller="pagination"
     data-action="scroll@document->pagination#scroll"
     data-pagination-url-value="<%= tweets_path %>"
     data-pagination-scope-value="<%= @scope %>"
     data-pagination-start-time-value="<%= @start_time %>"
     data-pagination-end-time-value="<%= @end_time %>"
     data-pagination-page-value="<%= @tweets.next_page %>" >
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
  <% end %>
</div>
<%= turbo_frame_tag("next_page_button") do %>
  <%= link_to "もっと！", path_to_next_page(@tweets), class: "btn btn-primary", data: { turbo_frame: "page_handler" } %>
<% end %>

app/views/tweets/index.turbo_stream.erb
<%= turbo_stream.append("tweets") do %>
  <%= render @tweets %>
<% end %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<!-- FIXME: indexで表示するコンテンツとshowで表示するコンテンツを分離したい -->
<!-- <%= image_tag @tweet.first_media_url || "", class: "w-100 border" %>
<p class="mt-3 mb-3"><%= @tweet.body %></p> -->

<div class="mb-3">
  <%= render @tweet %>
</div>
<div>
  <%= link_to "編集", edit_tweet_path(@tweet), class: "btn btn-primary" %>
</div>
<hr>
<div class="mb-3">
  <%= link_to "一覧に戻る", tweets_path, class: "btn btn-secondary"%>
</div>